# Generated by Django 5.2.8 on 2026-03-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMSSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=400)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
