# Generated by Django 5.2.8 on 2026-04-18 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0003_vmsalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitorpass',
            name='last_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
