# Generated by Django 5.2.8 on 2026-04-19 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0004_visit_host_visitorpass_last_scanned_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='escort_personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escort_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit',
            name='escort_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='vip_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitor',
            name='vip_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('id_verified', 'ID Verified'), ('pass_issued', 'Pass Issued'), ('inside', 'Inside'), ('exited', 'Exited'), ('denied', 'Denied'), ('pass_lost', 'Pass Lost')], default='registered', max_length=20),
        ),
    ]
