# Generated by Django 5.2.8 on 2026-04-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0005_visit_escort_personnel_visit_escort_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='escort_personnel',
            field=models.CharField(blank=True, help_text='Escort personnel identifier (can be user ID, name, or any text)', max_length=100, null=True),
        ),
    ]
