# Generated by Django 5.2.8 on 2026-04-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0006_change_escort_to_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityincident',
            name='issue_type',
            field=models.CharField(max_length=100),
        ),
    ]
